all: sprawozdanie1.pdf sprawozdanie2.pdf

sprawozdanie1.pdf: sprawozdanie1.tex
	texi2pdf sprawozdanie1.tex

sprawozdanie2.pdf: sprawozdanie2.tex
	texi2pdf sprawozdanie2.tex

clean:
	rm -rf sprawozdanie1.pdf sprawozdanie2.pdf *.log *.aux
