all: sprawozdanie1.pdf sprawozdanie2.pdf sprawozdanie3.pdf

sprawozdanie1.pdf: sprawozdanie1.tex
	texi2pdf sprawozdanie1.tex

sprawozdanie2.pdf: sprawozdanie2.tex
	texi2pdf sprawozdanie2.tex

sprawozdanie3.pdf: sprawozdanie3.tex
	texi2pdf sprawozdanie3.tex

clean:
	rm -rf sprawozdanie1.pdf sprawozdanie2.pdf sprawozdanie3.pdf *.log *.aux
